Specify the type of the method argument
It's necessary for the method follow the "-Wstrict-prototypes" warn.

Fixes an error:
    ../client/pk-offline-update.c:38:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
       38 | pk_offline_update_create_snapshot ()

Amends: 1.2.5-alt6~1
commit e5b75d424927717c8374cf043293469095dbe0ae
Author: Oleg Solovyov <mcpain@altlinux.org>

    offline-update: use timeshift before running transaction

(cherry picked from commit d61b5edfdd4f53f966aabadae193192db6222bd9)