Don't require function prototypes for C
Removes the function prototype check, because function prototypes aren't
always present in the source code.

Fixes errors like:
client/pk-offline-update.c:38:1: error: function declaration isn’t a
prototype [-Werror=strict-prototypes]