offline-update: use timeshift before running transaction
When snapshot is created, pre-update state is stored and can be rolled
back to in any cases, including but not limited to:
1) Update failed (transaction was aborted unexpectedly)
2) Update succeeded but packages are missing (removing window manager or
   whole desktop environment by dependency mistakes)
3) Update broke something (failure to open certain legacy formats
   dropped recently)
4) Updating stable -> unstable

cherry picked from commit 1.2.5-alt6~1
commit e5b75d424927717c8374cf043293469095dbe0ae
Author: Oleg Solovyov <mcpain@altlinux.org>

    offline-update: use timeshift before running transaction

and amended by:

commit d61b5edfdd4f53f966aabadae193192db6222bd9
Author: Dmitrii Fomchenkov <sirius@altlinux.org>
Date:   Fri Jan 17 11:43:42 2025 +0300

    Specify the type of the method argument

    It's necessary for the method follow the "-Wstrict-prototypes" warn.

    Fixes an error:
        ../client/pk-offline-update.c:38:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
           38 | pk_offline_update_create_snapshot ()

    Amends: 1.2.5-alt6~1
    commit e5b75d424927717c8374cf043293469095dbe0ae
    Author: Oleg Solovyov <mcpain@altlinux.org>

        offline-update: use timeshift before running transaction